### ISSUE TITLE
New sdk path

### ISSUE THREAD

**Issue by ypiguet** [speakinghedge/docker-esp-open-sdk#6]
Currently the correct value for SDK_BASE should be /home/espbuilder/esp-open-sdk/ESP8266_NONOS_SDK_V2.0.0_16_08_10 instead of /home/espbuilder/esp-open-sdk/esp_iot_sdk_v1.5.2 (line 48 of Dockerfile).

**Comment by speakinghedge** [comment]
let me check...

**Comment by speakinghedge** [comment]
...uhh - seems I already started to work on this a while ago (changed the Debian version to 8.7, added libtool-bin and changed the path to ENV SDK_BASE /home/espbuilder/esp-open-sdk/ESP8266_NONOS_SDK_V2.0.0_16_08_10 :smile:) - but never tested or pushed the changed Dockerfile. Well, I need to re-check my priorities. Thank you for the info / trigger - will push soon. Promised.

**Comment by speakinghedge** [comment]
fixed in ce89b84
